[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/manifest.json"
  to = "/.netlify/functions/addon/manifest.json"
  status = 200
  force = true

[[redirects]]
  from = "/stream/*"
  to = "/.netlify/functions/addon/stream/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/.netlify/functions/addon"
  status = 200
  force = true

# CSP específica para addon (segura y compatible)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), fullscreen=(), payment=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'none'; img-src 'self' data:; style-src 'unsafe-inline'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'"