[[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/manifest.json"
  to = "/.netlify/functions/addon/manifest.json"
  status = 200

[[redirects]]
  from = "/stream/*"
  to = "/.netlify/functions/addon/stream/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/addon"
  status = 200

# Seguridad y privacidad con CSP más flexible
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), fullscreen=(self), payment=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    # CSP más relajada: permite self, HTTPS externo, inline styles e imágenes
    Content-Security-Policy = "default-src 'self' https:; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https:; script-src 'self' https:; connect-src 'self' https:; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"