[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/manifest.json"
  to = "/.netlify/functions/addon/manifest.json"
  status = 200
  force = true

[[redirects]]
  from = "/:resource/:type/:id.json"
  to = "/.netlify/functions/addon/:resource/:type/:id.json"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/.netlify/functions/addon"
  status = 200
  force = true